---
# Required RBAC configuration
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium-migration-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cilium-migration-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "namespaces", "configmaps"]
  verbs: ["get", "list", "watch", "delete", "patch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflowtaskresults"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cilium-migration-binding
subjects:
- kind: ServiceAccount
  name: cilium-migration-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cilium-migration-role
  apiGroup: rbac.authorization.k8s.io